---
title: "SnattlePhy"
format: html
editor: visual
---

# Recreating Rattlesnake Rattle Phylogeny

Data from [Allf et al., 2016](https://www.journals.uchicago.edu/doi/full/10.1086/688017#_i5) & [Pyron et al., 2013](https://bmcecolevol.biomedcentral.com/articles/10.1186/1471-2148-13-93#MOESM1)

Carried out by Eric Witte, Vince Weber, & Shinji Yamamoto

## Installing Packages

```{r}
##Install Packages
#install.packages("ape")
#install.packages("ggtree")
#install.packages("here")
#install.packages("phytools")
#install.packages("readxl")
#install.packages("tidyverse")

#installing ggtree said that it needed a different version of R, but here's a work around
#if (!require("BiocManager", quietly = TRUE)) 
 #   install.packages("BiocManager")

#BiocManager::install("ggtree")



##Load Packages
library(ape)
library(ggtree)
library(here)
library(phytools)
library(readxl)
library(tidyverse)
```

## Pruning Colubridae & Viperidae From Squamata Phylogeny

Entire Squamata Tree

```{r}
##Squamate tree (Pyron et al.)
sqtree <- read.tree(here("data/12862_2013_2346_MOESM1_ESM.txt"))
plot(sqtree)

```

Matching the data and pruning the tree

```{r}
###prune tree; here is my [guide](http://blog.phytools.org/2011/03/prune-tree-to-list-of-taxa.html)

rat_dat <- readxl::read_excel(here("data/TableS1.xlsx")) #load and check data from Allf
view(rat_dat)

 #select only species we need for Allf
spec <- unique(rat_dat$Species) %>% 
# adding underscores to match the data format
  gsub(" ", "_", .)

pruned_tree <- keep.tip(sqtree, spec)
view(sqtree$tip.label)
view(spec1)
pruned_tree

write.tree(pruned_tree)
plot(pruned_tree)

#Checking whether rat_spec species are the same as in tip labels
#tibble(rat_spec = spec,
 #      in_tree = rat_spec %in% sqtree$tip.label) %>% 
  #view()

```

# Means of vibration rate and duration

```{r}
# eliminate NA, calculate the mean "Tail vibration rate (Max, Hz)" in rat_dat for each species, species name not in _

vib_mean_rate <- rat_dat %>%
  drop_na(`Tail vibration rate (Max, Hz)`) %>% 
  group_by(Species)%>%
  summarize(mean_rate = mean(`Tail vibration rate (Max, Hz)`),
            .groups = "drop")

view(vib_mean_rate)

# eliminate NA, calculate the mean "Tail vibration duration (Max, sec.)" in rat_dat for each species, species name not in _

dur_mean_rate <- rat_dat %>%
  drop_na(`Tail vibration duration (Max, sec.)`) %>% 
  group_by(Species)%>%
  summarize(mean_rate = mean(`Tail vibration duration (Max, sec.)`),
            .groups = "drop")

view(dur_mean_rate)

#check ?str_replace to change spaces into _ in each tibble


```
